### ISSUE TITLE
Kartotek: "Visar alla" försvinner vid nyladdning av artiklar

### ISSUE THREAD

**Issue by albka735** [jcmandersson/Operation#5]
Efter man kryssat i "Visa alla" och gör en sökning eller skrollar längst ner på sidan och nya artiklar laddas så ställs allt om så det ser ut som när "Visa alla" är urkyssat. Jag har inte så jättestor koll på hur jag ska fixa detta. Skulle @DanielRapp kunna kolla på det?

![shiit](https://cloud.githubusercontent.com/assets/10847018/7161056/4305a362-e38d-11e4-8a2b-98370943844f.png)
![shiiiiit](https://cloud.githubusercontent.com/assets/10847018/7161052/3a323200-e38d-11e4-860a-638156c9ba96.png)

**Comment by albka735** [comment]
Märkte nu att det händer när man trycker någonstans på en rad också.

**Comment by DanielRapp** [comment]
Anledningen är detta lilla fulhacket (av @jcmandersson):

``` javascript
$('#toggle-fields').click(function() {
  $('.toggable').toggleClass('hidden');
});
```

Bara så alla vet. För att kartoteket ska kunna renderas, och inte bugga när det ändras, så behöver all information om den (hela "modellen") finnas i articles.data. Varje gång kartoteket ändras så renderas templaten om, och den använder endast data från this.data för att göra det.
Så det ovan är i princip som att ändra view:n direkt, utan att också ändra modellen.

Jag kan fixa det den här gången, men bara något att tänka på ifall ni ändrar kartotek.js.

**Comment by jcmandersson** [comment]
Förtal! Inte jag som skrivit den koden. 

—

**Comment by DanielRapp** [comment]
Helt korrekt! Sorry!
Git blame säger att detta är @albka735 som vart inne och lekt :)
https://github.com/jcmandersson/Operation/blame/master/public/js/kartotek.js#L318
(Men jag fixar det som sagt.)

**Comment by DanielRapp** [comment]
Öppnar denna igen :( Funkar lokalt men inte på halvbra.se. Jag har föreläsning till 12, och går till creactive, så kommer ha ont om tid att fixa detta. Om @jcmandersson eller någon kan ta en tit så skulle det vara super! (Annars revert:a till @albka735 ändring.)

**Comment by DanielRapp** [comment]
Tror det har något med kolumner som är tomma att göra. Lokalt kör jag bara med artiklar som har data för varje fält (och lokalt funkar det) men på halvbra.se så finns det data som inte har värden i varje fält.

**Comment by DanielRapp** [comment]
@albka735 Fixade det! Danke!
